server:
  port: 8000
spring:
  liquibase:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    user: sa
    password:
    enabled: true
    change-log: classpath:db/db.changelog.yaml
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      port: 8082
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password:
bookingEndsBeforeScreeningInMinutes: 15

